language: erlang
script: "make all"
before_install: dialyzer --build_plt --apps erts kernel stdlib compiler
otp_release:
   - 17.0-rc1
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
